#!/bin/bash

echo " ____        _     _     _           _____   __  __ _                     "
echo "/ ___| _   _| |__ | |   (_)_ __ ___ |___ /  |  \/  (_)_ __ _ __ ___  _ __ "
echo "\___ \| | | | '_ \| |   | | '_ ` _ \  |_ \  | |\/| | | '__| '__/ _ \| '__|"
echo " ___) | |_| | |_) | |___| | | | | | |___) | | |  | | | |  | | | (_) | |   "
echo "|____/ \__,_|_.__/|_____|_|_| |_| |_|____/  |_|  |_|_|_|  |_|  \___/|_|   "
sleep 5

echo "******************************************************************************************"
echo "*** Restoring Original compliments.js from ~/MagicMirror/modules/default/compliments/. ***"
echo "******************************************************************************************"
sleep 5

if [ -f ~/MagicMirror/modules/default/compliments/original_compliments.js ]; then
    rm -f ~/MagicMirror/modules/default/compliments/compliments.js
    echo "The Custom compliments.js has been removed."
	rm -f ~/MagicMirror/modules/default/compliments/original_compliments.js ~/MagicMirror/modules/default/compliments/compliments.js
else
    echo "File original_compliments.js not found in ~/MagicMirror/modules/default/compliments/"
fi

echo "****************************************************************"
echo "*** Restoring Original config.js from ~/MagicMirror/config/. ***"
echo "****************************************************************"
sleep 5

if [ -f ~/MagicMirror/config/original_config.js ]; then
    rm -f ~/MagicMirror/config/config.js
    echo "The Custom compliments.js has been removed."
	rm -f ~/MagicMirror/modules/default/compliments/original_config.js ~/MagicMirror/modules/default/config.js
else
    echo "File original_compliments.js not found in ~/MagicMirror/modules/default/compliments/"
fi

echo "****************************************************"
echo "***  - All operations completed successfully.  - ***"
echo "****************************************************"
sleep 5
